// <auto-generated />
namespace Game_AVP2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ItemsnewProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemsnewProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201608110811010_ItemsnewProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
